json.active notification_preference.active
json.user1WeekBefore notification_preference.user_1_week_before unless notification_preference.user.organization_manager
json.user1DayBefore notification_preference.user_1_day_before unless notification_preference.user.organization_manager
json.user1HourBefore notification_preference.user_1_hour_before unless notification_preference.user.organization_manager
json.userWhenManagerCancelAppointment notification_preference.user_when_manager_cancel_appointment unless notification_preference.user.organization_manager
json.manager_appointmentRequested notification_preference.manager_appointment_requested if notification_preference.user.organization_manager
json.manager_appointmentCancelled notification_preference.manager_appointment_cancelled if notification_preference.user.organization_manager